version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dpc-safe
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

  aggregation:
    image: ${ECR_HOST:-755619740999.dkr.ecr.us-east-1.amazonaws.com/dpc-aggregation}:latest
    ports:
      - "9901:9900"
    env_file:
      - ./ops/config/decrypted/local.env
    environment:
      - ENV=local
      - JACOCO=${REPORT_COVERAGE}
    depends_on:
      - db
    volumes:
      - export-volume:/app/data
      - ./jacocoReport/dpc-aggregation:/jacoco-report

  attribution:
    image: ${ECR_HOST:-755619740999.dkr.ecr.us-east-1.amazonaws.com/dpc-attribution}:latest
    depends_on:
      - db
    environment:
      - ENV=local
      - JACOCO=${REPORT_COVERAGE}
    ports:
      - "3500:8080"
      - "9902:9900"
    volumes:
      - ./jacocoReport/dpc-attribution:/jacoco-report

  api:
    image: ${ECR_HOST:-755619740999.dkr.ecr.us-east-1.amazonaws.com/dpc-api}:latest
    ports:
      - "3002:3002"
      - "9903:9900"
    environment:
      - attributionURL=http://attribution:8080/v1/
      - ENV=local
      - JACOCO=${REPORT_COVERAGE}
      - exportPath=/app/data
      - JVM_FLAGS=-Ddpc.api.authenticationDisabled=${AUTH_DISABLED:-false}
    depends_on:
      - attribution
    volumes:
      - export-volume:/app/data
      - ./jacocoReport/dpc-api:/jacoco-report

  consent:
    image: ${ECR_HOST:-755619740999.dkr.ecr.us-east-1.amazonaws.com/dpc-consent}:latest
    depends_on:
      - db
    environment:
      - ENV=local
      - JACOCO=${REPORT_COVERAGE}
    ports:
      - "3600:3600"
      - "9004:9900"
    volumes:
      - ./jacocoReport/dpc-consent:/jacoco-report

  start_core_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432

  start_api_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - attribution
      - aggregation
    command: attribution:8080 aggregation:9900

  start_api:
    image: dadarek/wait-for-dependencies
    depends_on:
      - api
    command: api:3002

volumes:
  export-volume:
    driver: local
    driver_opts:
      type: none
      device: /tmp
      o: bind